services:
  php-fpm:
    build:
      dockerfile: docker-env/prod/php-fpm.Dockerfile
    volumes:
      - .:/var/www/html
    expose:
      - '9000'

  nginx:
    build:
      context: .
      dockerfile: docker-env/prod/nginx.Dockerfile
    volumes:
      - ./public:/var/www/html/public
    ports:
      - '8081:80'
      - '8443:443'
    depends_on:
      - php-fpm
