services:
    nginx:
        container_name: furries-board-dev-nginx
        build:
            dockerfile: ./nginx.Dockerfile
        ports:
            - '8081:80'
            - '8443:443'
            - '9000'
            - '9003'
        volumes:
            - .:/var/www/html
            - ./docker-env/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker-env/nginx/certs:/etc/nginx/certs # 放 ssl 憑證的地方
        environment:
            - TZ=Asia/Taipei

    # 資料庫
    mariadb:
        image: mariadb:10.11.11
        container_name: furries-board-dev-mariadb
        ports:
            - '3306:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - TZ=Asia/Taipei
        volumes:
            - ./database/data:/var/lib/mysql
        stop_grace_period: 10s

    # 資料庫管理介面
    phpmyadmin:
        image: phpmyadmin
        ports:
            - '8082:80'
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=host.docker.internal
            - UPLOAD_LIMIT=300M

    # Redis 快取
    # redis:
    #     image: redis:7-alpine
    #     container_name: furries-board-dev-redis
    #     ports:
    #         - '6379:6379'
    #     volumes:
    #         - ./docker-env/redis/data:/data
    #     environment:
    #         - TZ=Asia/Taipei

    # Laravel Echo
    # echo-server:
    #     build:
    #         dockerfile: ./docker-env/echo-server.Dockerfile
    #     container_name: furries-board-dev-echo
    #     volumes:
    #         - .:/app
    #     ports:
    #         - '6001:6001'
    #     depends_on:
    #         - redis
    #     environment:
    #         - TZ=Asia/Taipei
