services:
  nginx:
    container_name: furries-board-nginx
    build:
      dockerfile: ./docker-env/dev/Dockerfile
    ports:
      - '8081:80'
      - '8443:443'
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=development
      - TZ=Asia/Taipei
    command: supervisord -c /etc/supervisord.conf

  # 資料庫
  mariadb:
    container_name: furries-board-mariadb
    image: mariadb:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Taipei
    volumes:
      - ./database/data:/var/lib/mysql
    stop_grace_period: 10s

  # 資料庫管理介面
  phpmyadmin:
    image: phpmyadmin
    ports:
      - '8082:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=host.docker.internal
      - UPLOAD_LIMIT=300M
    depends_on:
      - mariadb
